### ISSUE TITLE
Sudden speed up

### ISSUE THREAD

**Issue by bogus105** [risitt/kissStepper#3] opened 2017-10-22 07:51 UTC
Hi,
firstly thank you for a great tool. My setup: arduino uno board, arduino nano board with DCservoSTEP/DIR software onboard (serve as servo drive, PID tunned), IBT-2 h-bridge (based on BTN7960 chips), electrocraft PMDC servomotor with 250 ppr encoder (1000 pulses in quadrature).

Uploaded kissStepper example from library: serial control

While playing around with servo via serial i found wierd behavior: i tried to command a long run, say from 0 to 100 000 ( <goto 100000> ) which is 100 revolutions of motor shaft @ 1000pulses/rev encoder, acceleration was set to 10 000 pulses/sec2 and maxspeed was set to 30 000 pulses/sec (1800rpm). Motor starts slowly and accelerates to certain speed then i look like acceleration stops for a while and then it suddenly accelerates to max speed in a blink of an eye. 

Got ideas what is going on?
Regards,
Bogi

**Comment by risitt** [comment] 2017-11-07 00:03
Hi Bogi,

I will see if I can replicate this issue with a normal stepper motor using the information you provided. Stay tuned.

**Comment by risitt** [comment] 2017-11-07 00:17
I have replicated this issue, fix should come soon. Thank you very much for making me aware of this problem!

**Comment by risitt** [comment] 2017-11-07 02:31
Quick question for you. When your motor hits maximum speed, does it move properly?

I ask because my stepper tops out at about 1000 st/s before it stalls, so I can't test your situation "directly". I'll have to break out a logic analyzer for this one!

As I'm a bit busy with the day job, this might have to wait until the weekend for me to poke at. It looks like there's an issue with the acceleration and deceleration logic at least.

Can you turn acceleration off (set it to 0) and let me know if your servo moves as you'd expect? 

If this risks damaging your servo by stalling it, do not attempt it of course. Perhaps an alternative would be to reduce acceleration greatly, and use \<move forward\>, and see if it does a nice linear ramp up to max speed. Periodically send \<getcurspeed\> to see progress. If anything weird happens, let me know.

Out of curiosity, what servo and drive software are you using? I'd consider obtaining such things for proper testing of high speed operation.

**Comment by bogus105** [comment] 2017-11-07 14:25
Hi, thank you for response. I'll be at work in 3 days and i have the setup there. I'll try to do as you suggest. If my memory serves my right top speed i could go was ca. 20000 encoder ticks per second @ 125ppr encoder (500 pulses in quadrature) so it gives 2400rpm. 
As for servo setup i'm using please kindly see my vid:

https://youtu.be/icBFc65dfvA

and some earlier setup w/ smaller h-bridge and motor:

https://www.youtube.com/watch?v=vHufLMh4xEI

I'm trying to figure out why my big servo doesn't move to desired position in a blink of an eye. Don't know if it is PID tuning issue or PID library issue:/ It finally reach commanded position but it take some seconds. The error isn't big but there is room for improvements for sure. 
My setup is powered from 19VDC laptop supply. I'll try to hook it up to 28VDC power supply for more juice. Curious if it will help to solve positioning problem (i'm assuming more voltage give more dynamics to PMDC motor?).

**Comment by risitt** [comment] 2017-11-08 00:59
Hi Bogi,

What you're building there looks pretty cool. Unfortunately, I've figured out the root cause of the problem you are experiencing, and it pretty much makes my library unusable for you at the moment.

Here is a benchmark of the work() method running under the parameters you provided:

work() benchmark with 30000 st/s^2 acceleration
Testing 50 st/s: 13.99 us avg over 290426 calls
Testing 100 st/s: 14.11 us avg over 142096 calls
Testing 200 st/s: 14.56 us avg over 69638 calls
Testing 400 st/s: 16.14 us avg over 32743 calls
Testing 800 st/s: 24.87 us avg over 12714 calls
Testing 1600 st/s: 103.83 us avg over 3414 calls
Testing 3200 st/s: 145.29 us avg over 3414 calls
Testing 6400 st/s: 145.29 us avg over 3414 calls
Testing 12800 st/s: 145.30 us avg over 3414 calls
Testing 25600 st/s: 145.30 us avg over 3414 calls

As you can see, at higher max speeds, the work function requires more time per run, because there's a bunch of very expensive division operations that occur every time speed is incremented/decremented. At higher max speeds, more time is spent accelerating/decelerating, and so more division operations.

And the duration required to execute the work() function can exceed the interval between STEP pin changes (stepInterval below):

stepsPerSec | uStepsPerSec | stepInterval
-- | -- | --
50 | 200 | 2500
100 | 400 | 1250
200 | 800 | 625
400 | 1600 | 312.5
800 | 3200 | 156.25
1600 | 6400 | 78.125
3200 | 12800 | 39.0625
6400 | 25600 | 19.53125
12800 | 51200 | 9.765625
25600 | 102400 | 4.8828125

What this means for you is that the maximum speed you can get away with, if you use acceleration, is about 800 steps/sec.

Without acceleration, it gets much better but still not amazing:

work() benchmark without acceleration
Testing 50 st/s: 9.28 us avg over 431055 calls
Testing 100 st/s: 9.32 us avg over 214688 calls
Testing 200 st/s: 9.40 us avg over 106384 calls
Testing 400 st/s: 9.55 us avg over 52353 calls
Testing 800 st/s: 9.87 us avg over 25336 calls
Testing 1600 st/s: 10.57 us avg over 11827 calls
Testing 3200 st/s: 12.62 us avg over 4954 calls
Testing 6400 st/s: 14.63 us avg over 3200 calls
Testing 12800 st/s: 14.71 us avg over 3200 calls
Testing 25600 st/s: 14.41 us avg over 3200 calls

So you might be able to get away with 6400 steps/sec without acceleration.

Although I intend to do some optimization work with the acceleration code, I will never get the library in a state where it can run at 30000 steps/sec, with acceleration on, with an Arduino UNO.

But I don't think your project is a lost cause.

Consider the Teensy 3.2 which is MUCH faster than an Arduino UNO. You can even overclock it to 96 MHz. That's 6 times the speed of the Arduino UNO, so my crude math suggests you should be able to reach 30000 steps/sec without acceleration.

Teensy is supposedly compatible with Arduino, so I think you can just program it with my library and your existing code. But I have never tried this.

I have a pair of Teensy units. Since I'm intrigued as to whether I can get this library running nicely at high speed on one of them, I'll take some time over the next little while to experiment with them and try to optimize the library's acceleration code as well. If I make any progress, I'll let you know here!

**Comment by risitt** [comment] 2017-11-08 01:53
Just as a note to myself, the following link describes a method for linear acceleration that does not rely on division operators:

https://www.eetimes.com/document.asp?doc_id=1276928

I will attempt to implement something similar. While this will help, a faster processor is still a must for very high speeds.

**Comment by risitt** [comment] 2017-12-06 00:58
An update:

I realize my library probably won't work on a Teensy. I'll consider adding support for it in the future.

However, I am making good progress on addressing the performance issues.

Using the application note from Atmel, "AVR446:  Linear speed control of stepper motor", I am now generating speed profiles and working on approximating linear acceleration.

This has, however, required a complete overhaul of the library and many API changes. Once thoroughly tested and documentation updated, I'll update everything here.

There are even faster ways to accomplish linear acceleration (lots of application notes scattered across the web) but they all seem to use a similar approach with successive layers of approximation. Implementing the algorithm in ATMEL's research note will put the library in a very good state for further improvements.

**Comment by risitt** [comment] 2018-11-03 21:13
Hello Bogi,

Although it has taken a while, I have finalized me rewrite of this library to address the acceleration performance issues. You should find that it performs much better now!

I have also added official support for the Teensyduino platform. Testing on a Teensy 3.1 device was initially  surprising to me - the performance increase versus the Arduino UNO is extreme. From what I can tell this has little to do with the actual rated speed of the processor, but rather the fact that the Teensy is a 32 bit processor with hardware support for floating point math.

So, I'm closing this issue, as I believe I have address your problem! Let me know how your future experimentation goes, and thank you for reporting the original problem.

**Closed as completed by risitt** 2018-11-03 21:13 UTC
